modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="limelib"
version="1.0.0"
displayName="LimeLib"
displayURL="https://minecraft.curseforge.com/projects/limelib"
credits="Thanks for this example mod goes to Java"
authors="KidsDontPlay"
description='''
A Library for my other mods
'''

[[dependencies.limelib]]
    modId="forge"
    mandatory=true
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.limelib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2,1.15)"
    ordering="NONE"
    side="BOTH"
